### ISSUE TITLE
preserve edited PR body when updating a PR

### ISSUE THREAD

**Issue by HarmenM** [annervisser/pr-cli#185]
A typical flow is to create a PR using `pr-cli` and afterwards writing a story screenshots in the PR Body on Github.

When using the PR update `pr-cli upr`  command it would be nice if only the generated list with commits were updated, leaving any additions intact.

**Comment by annervisser** [comment]
@HarmenM https://github.com/annervisser/pr-cli/releases/tag/1.8.0

**Comment by HarmenM** [comment]
Great, thank you 😄
